"""Initial schema

Revision ID: a676e68ed96f
Revises: 
Create Date: 2026-06-27 16:42:07.218212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'a676e68ed96f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('bin', sa.String(length=12), nullable=True),
    sa.Column('contact_email', sa.String(length=256), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('partner_id')
    )
    op.create_index(op.f('ix_partners_bin'), 'partners', ['bin'], unique=False)
    op.create_index(op.f('ix_partners_name'), 'partners', ['name'], unique=False)
    op.create_table('services',
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=512), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('icd_code', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embedding', Vector(dim=768), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_service_name'), 'services', ['service_name'], unique=False)
    op.create_table('price_documents',
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_format', sa.Enum('pdf', 'docx', 'xlsx', 'scan_pdf', name='fileformat'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parse_status', sa.Enum('pending', 'processing', 'done', 'error', 'needs_review', name='parsestatus'), nullable=False),
    sa.Column('parse_log', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_price_documents_partner_id'), 'price_documents', ['partner_id'], unique=False)
    op.create_table('price_items',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('service_name_raw', sa.String(length=1024), nullable=False),
    sa.Column('service_code_source', sa.String(length=128), nullable=True),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('price_resident_kzt', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_nonresident_kzt', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_original', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency_original', sa.Enum('KZT', 'USD', 'RUB', name='currency'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_note', sa.String(length=1024), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_method', sa.Enum('exact', 'synonym', 'fuzzy', 'embedding', 'manual', 'none', name='matchmethod'), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['price_documents.doc_id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.partner_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_price_items_doc_id'), 'price_items', ['doc_id'], unique=False)
    op.create_index(op.f('ix_price_items_is_active'), 'price_items', ['is_active'], unique=False)
    op.create_index(op.f('ix_price_items_needs_review'), 'price_items', ['needs_review'], unique=False)
    op.create_index(op.f('ix_price_items_partner_id'), 'price_items', ['partner_id'], unique=False)
    op.create_index(op.f('ix_price_items_service_id'), 'price_items', ['service_id'], unique=False)
    op.create_index(op.f('ix_price_items_service_name_raw'), 'price_items', ['service_name_raw'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_items_service_name_raw'), table_name='price_items')
    op.drop_index(op.f('ix_price_items_service_id'), table_name='price_items')
    op.drop_index(op.f('ix_price_items_partner_id'), table_name='price_items')
    op.drop_index(op.f('ix_price_items_needs_review'), table_name='price_items')
    op.drop_index(op.f('ix_price_items_is_active'), table_name='price_items')
    op.drop_index(op.f('ix_price_items_doc_id'), table_name='price_items')
    op.drop_table('price_items')
    op.drop_index(op.f('ix_price_documents_partner_id'), table_name='price_documents')
    op.drop_table('price_documents')
    op.drop_index(op.f('ix_services_service_name'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_partners_name'), table_name='partners')
    op.drop_index(op.f('ix_partners_bin'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
